apiVersion: v1
kind: Service
metadata:
  name: imageclassifier
spec:
  type: LoadBalancer
  selector:
    app: imageclassifier  # This should match the labels in your Deployment YAML
  ports:
    - port: 80            # The port on which the service listens
      targetPort: 8501     # The port to which traffic is forwarded to the pods
